"""
Unified rewrite of track unit / index pages.

For every .qmd under track_* (and /a_propos /bildungsplan /programme /index
/remerciements /bibliographie /annexes/*), pull the **original body** from git
HEAD, then:

  1. apply translation substitutions (German → French) on visible content;
  2. apply gloss annotations (append « German » after the first French
     occurrence per file) — *but skip a gloss rule if the German term
     already appears anywhere in the body*, so longer phrases that contain
     a shorter one don't get double-annotated.

Frontmatter is regenerated by `restore_yaml_frontmatter.py` separately, so
this script touches the body only.
"""
from __future__ import annotations
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXCLUDE_DIRS = {".git", "docs", "_resources", "_scripts"}
SKIP_FILES = {
    "bibliographie.qmd",
    "datenschutz.qmd",
    "impressum.qmd",
    "haftungsausschluss.qmd",
}

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
H1_AFTER_FM_RE = re.compile(r"^# (?!#)(.+)$", re.MULTILINE)

# ---------------------------------------------------------------------------
# Translation rules (body only — no indentation-killing rules)
# ---------------------------------------------------------------------------
SUBS: list[tuple[str, str]] = [
    # branding
    (r"\bFLE BW ·", "FLE ·"),
    (r"\bFLE BW —", "FLE —"),
    (r"\bFLE-BW\b", "FLE"),
    (r"\bEFL BW\b", "EFL"),
    (r"\bBW-(conforme|aligné|alignée|alignés|alignées)\b",
     "conforme au référentiel régional"),

    # KLASSE / Klasse / Kl.
    (r"\bKLASSE (\d+)", r"CLASSE \1"),
    (r"\bKL\. (\d+)", r"CL. \1"),
    (r"\bKlassen (\d+)–(\d+)\b", r"classes \1–\2"),
    (r"\bKlasse (\d+) à (\d+)\b", r"classes \1 à \2"),
    (r'\bKlasse (\d+)\b', r'classe \1'),
    (r"\bKl\. (\d+)–(\d+)\b", r"cl. \1–\2"),
    (r"\bKl\. (\d+)\b", r"cl. \1"),
    (r"\bKlassenstufe\b", "niveau de classe"),

    # diploma / school types
    (r"\bGymnasium\b", "lycée"),
    (r"\(Gymnasium\)", "(lycée)"),
    (r"\bRealschule\b", "collège"),
    (r"\bGesamtschule\b", "établissement secondaire"),

    # Bildungsplan tokens (long phrases first)
    (r"Bildungsplan-BW Französisch", "référentiel officiel de français"),
    (r"\bBildungsplan-BW\b", "référentiel régional"),
    (r"Bildungsplan gymnasiale Oberstufe 2021 Baden-Württemberg",
     "référentiel du cycle terminal (2021)"),
    (r"Bildungsplan gymnasiale Oberstufe 2021",
     "référentiel du cycle terminal (2021)"),
    (r"Bildungsplan 2016 Sekundarstufe I — Französisch \(2\.\s*Fremdsprache\)",
     "référentiel du secondaire I (2016) — Français (2ᵉ langue vivante)"),
    (r"Bildungsplan 2016 Baden-Württemberg",
     "référentiel régional (2016)"),
    (r"\bBildungspläne\b", "référentiels"),
    (r"\bBildungsplan\b", "référentiel"),
    (r"Land Bade-Wurtemberg", "ayants droit régionaux"),
    (r"\bBade-Wurtemberg\b", ""),
    (r"\bBaden-Württemberg\b", ""),

    # skills (long phrases first)
    (r"Sprechen — an Gesprächen teilnehmen",
     "Expression orale — interaction"),
    (r"Sprechen — zusammenhängendes monologisches Sprechen",
     "Expression orale — production en continu"),
    (r"zusammenhängendes monologisches Sprechen",
     "production orale en continu"),
    (r"Hör-/Hörsehverstehen", "Compréhension orale et audiovisuelle"),
    (r"\bLeseverstehen\b", "Compréhension écrite"),
    (r"\bSprechen \(Dialog\)", "Expression orale (interaction)"),
    (r"\bSprechen \(Monolog\)", "Expression orale (production en continu)"),
    (r"\bSchreiben\b", "Expression écrite"),
    (r"\bSprechen\b", "Expression orale"),
    (r"\bHören\b", "Compréhension orale"),
    (r"\bLesen\b", "Compréhension écrite"),
    (r"\bSprachmittlung\b", "médiation linguistique"),
    (r"\bModul\b", "Module"),
    (r"Verfügen über sprachliche Mittel — Wortschatz",
     "Moyens linguistiques — lexique"),
    (r"Verfügen über sprachliche Mittel — Grammatik",
     "Moyens linguistiques — grammaire"),
    (r"Verfügen über sprachliche Mittel — Aussprache",
     "Moyens linguistiques — prononciation"),
    (r"Soziokulturelles Orientierungswissen / Themen",
     "Connaissances socio-culturelles / thèmes"),
    (r"Interkulturelle kommunikative Kompetenz",
     "Compétence interculturelle communicative"),
    (r"Funktionale kommunikative Kompetenz",
     "Compétence communicative fonctionnelle"),
    (r"Text- und Medienkompetenz",
     "Compétence textuelle et médiatique"),
    (r"\bBezeichnung\b", "Désignation"),
    (r"\bInhalt\b", "Contenu"),
    (r"\bSprache\b", "Langue"),
    (r"\bsehr gut\b", "très bien"),
    (r"\bSchriftliche\b", "Écrit"),
    (r"\bMündliche\b", "Oral"),
    (r"Erwartungshorizont", "horizon d'attente"),

    # diplomas / exams
    (r"Mittlerer Bildungsabschluss", "diplôme intermédiaire"),
    (r"Mittlere Reife", "diplôme intermédiaire"),
    (r"Hauptschulabschluss", "diplôme de fin de scolarité obligatoire"),
    (r"Allgemeine Hochschulreife", "baccalauréat équivalent"),
    (r"Kommunikationsprüfung", "épreuve communicative"),
    (r"Abitur Lf BW", "épreuve finale (option d'approfondissement)"),
    (r"Abitur Bf BW", "épreuve finale (option de base)"),
    (r"\bAbitur Lf\b", "épreuve finale (option d'approfondissement)"),
    (r"\bAbitur Bf\b", "épreuve finale (option de base)"),
    (r"\bAbitur\b", "épreuve finale"),
    (r"\bKlassenarbeit\b", "devoir surveillé"),
    (r"\bKlausur\b", "épreuve"),
    (r"\bNotenschlüssel\b", "barème de notes"),
    (r"\bBasisfach\b", "option de base"),
    (r"\bLeistungsfach\b", "option d'approfondissement"),
    (r"\bSek I\b", "secondaire I"),
    (r"\bSek II\b", "secondaire II"),
    (r"\bKursstufe\b", "cycle terminal"),
    (r"\bBORS\b", "stage d'orientation"),
    (r"\bBOGY\b", "stage d'orientation au lycée"),

    # Niveau / Filière
    (r"Niveau G\+M \(Kl\. (\d+)–(\d+)\)", r"Filière G+M (cl. \1–\2)"),
    (r"Niveau E \(Kl\. (\d+)–(\d+)\)", r"Filière E (cl. \1–\2)"),

    # Module : <skill>
    (r"\bModule ?: ?Expression orale\b", "Module : Expression orale"),

    # Specific BW removals (before bare " BW" cleanup)
    (r"15/15 BW", "15/15"),
    (r"15 points BW", "15 points"),
    (r"contexte scolaire BW", "contexte scolaire local"),
    (r"format épreuve finale écrit Lf BW",
     "format de l'épreuve finale écrite (option d'approfondissement)"),
    (r"5 critères d'évaluation \(KMK / BW\)",
     "5 critères d'évaluation (officiels)"),
    (r"5 critères KMK \(Lf BW\)",
     "5 critères officiels (option d'approfondissement)"),
    (r"Conditions du mock final \(Lf BW\)",
     "Conditions du mock final (option d'approfondissement)"),
    (r"\(note allemande sur 15 points BW\)", "(note sur 15 points)"),
    (r"BW Niveau M", "Niveau M"),
    (r"barème de notes typique BW", "barème de notes typique"),
    (r"Indications de notation \(M, indicatives BW\)",
     "Indications de notation (M, indicatives)"),
    (r"\bau format BW\b", "au format officiel"),
    (r"(?<= )BW(?=[\s.,;:\)\"])", ""),
    (r"\(BW\)", ""),

    # capitalisation fixes after substitutions
    (r"\[référentiel\]", "[Référentiel]"),
    (r"^(#+ )référentiel", r"\1Référentiel"),
    (r"^(#+ )devoir surveillé", r"\1Devoir surveillé"),
    (r"^(#+ )épreuve", r"\1Épreuve"),
    (r"^(#+ )barème", r"\1Barème"),
    (r"^(#+ )médiation", r"\1Médiation"),
    (r"^(#+ )classe ", r"\1Classe "),
    (r"^(\* +|- +|\d+\. +)référentiel", r"\1Référentiel"),
    (r"^devoir surveillé", "Devoir surveillé"),
    (r"\. devoir surveillé", ". Devoir surveillé"),
    (r"\. classe ", ". Classe "),
    (r"\. barème de notes", ". Barème de notes"),
    (r"\. référentiel", ". Référentiel"),
    (r"\. médiation", ". Médiation"),
    (r"\. épreuve", ". Épreuve"),
]

# ---------------------------------------------------------------------------
# Gloss pairs: (translated, German). Longer phrases first.
# Each entry is appended once per file *only if* the German term is not
# already present in the body (this prevents nested-gloss duplication).
# ---------------------------------------------------------------------------
GLOSSES: list[tuple[str, str]] = [
    ("Expression orale — interaction", "Sprechen — an Gesprächen teilnehmen"),
    ("Expression orale — production en continu",
     "Sprechen — zusammenhängendes monologisches Sprechen"),
    ("Compréhension orale et audiovisuelle", "Hör-/Hörsehverstehen"),
    ("Compréhension écrite", "Leseverstehen"),
    ("Expression écrite", "Schreiben"),
    ("Expression orale", "Sprechen"),
    ("Compréhension orale", "Hören"),
    ("Médiation linguistique", "Sprachmittlung"),
    ("médiation linguistique", "Sprachmittlung"),
    ("Compétence interculturelle communicative",
     "Interkulturelle kommunikative Kompetenz"),
    ("Compétence communicative fonctionnelle",
     "Funktionale kommunikative Kompetenz"),
    ("Compétence textuelle et médiatique", "Text- und Medienkompetenz"),
    ("Connaissances socio-culturelles / thèmes",
     "Soziokulturelles Orientierungswissen / Themen"),
    ("Moyens linguistiques — lexique",
     "Verfügen über sprachliche Mittel — Wortschatz"),
    ("Moyens linguistiques — grammaire",
     "Verfügen über sprachliche Mittel — Grammatik"),
    ("Moyens linguistiques — prononciation",
     "Verfügen über sprachliche Mittel — Aussprache"),
    ("référentiel régional", "Bildungsplan"),
    ("référentiel", "Bildungsplan"),
    ("devoir surveillé", "Klassenarbeit"),
    ("épreuve communicative", "Kommunikationsprüfung"),
    ("épreuve finale", "Abitur"),
    ("option de base", "Basisfach"),
    ("option d'approfondissement", "Leistungsfach"),
    ("diplôme intermédiaire", "Mittlerer Bildungsabschluss"),
    ("diplôme de fin de scolarité obligatoire", "Hauptschulabschluss"),
    ("baccalauréat équivalent", "Allgemeine Hochschulreife"),
    ("cycle terminal", "Kursstufe"),
    ("stage d'orientation au lycée", "BOGY"),
    ("stage d'orientation", "BORS"),
    ("barème de notes", "Notenschlüssel"),
    ("horizon d'attente", "Erwartungshorizont"),
    ("lycée", "Gymnasium"),
    ("collège", "Realschule"),
    ("établissement secondaire", "Gesamtschule"),
]


def transform(text: str) -> str:
    for pat, rep in SUBS:
        text = re.sub(pat, rep, text, flags=re.MULTILINE)
    return text


def add_glosses(body: str) -> str:
    for fr, de in GLOSSES:
        # Skip if German term already present anywhere in the body
        if de in body:
            continue
        # Match `fr` only when followed by a non-letter (so "référentiel"
        # does not match inside "référentiels" and split it)
        pattern = re.escape(fr) + r"(?![a-zA-ZàâäéèêëïîôöùûüçœÀÂÄÉÈÊËÏÎÔÖÙÛÜÇŒ])"
        m = re.search(pattern, body)
        if not m:
            continue
        body = body[:m.end()] + f" (« {de} »)" + body[m.end():]
    return body


def strip_explicit_h1(body: str) -> str:
    m = H1_AFTER_FM_RE.search(body)
    if not m:
        return body
    line_start = body.rfind("\n", 0, m.start()) + 1
    line_end = m.end()
    if line_end < len(body) and body[line_end] == "\n":
        line_end += 1
    if line_end < len(body) and body[line_end] == "\n":
        line_end += 1
    return body[:line_start] + body[line_end:]


def git_show(path: Path) -> str | None:
    rel = path.relative_to(ROOT).as_posix()
    try:
        return subprocess.check_output(
            ["git", "show", f"HEAD:{rel}"], cwd=ROOT, encoding="utf-8"
        )
    except subprocess.CalledProcessError:
        return None


def process(path: Path, manual: bool) -> bool:
    current = path.read_text(encoding="utf-8")
    if manual:
        # Manually rewritten file — keep frontmatter & body, only de-duplicate
        # glosses and ensure no nested ones. We rebuild the body by stripping
        # any existing « German » glosses and re-applying once with de-dupe.
        cm = FRONTMATTER_RE.match(current)
        if not cm:
            return False
        fm = current[: cm.end()]
        body = current[cm.end():]
        # remove existing parenthetical glosses *only* for known German terms
        for _, de in GLOSSES:
            body = re.sub(
                r"\s*\(« " + re.escape(de) + r" »\)", "", body
            )
        body = strip_explicit_h1(body)
        body = add_glosses(body)
        new_text = fm + body
    else:
        original = git_show(path)
        if original is None:
            return False
        om = FRONTMATTER_RE.match(original)
        if not om:
            return False
        orig_body = original[om.end():]
        new_body = strip_explicit_h1(orig_body)
        new_body = transform(new_body)
        new_body = add_glosses(new_body)
        new_fm = transform(om.group(1))
        new_text = f"---\n{new_fm}\n---\n" + new_body

    if new_text != current:
        path.write_text(new_text, encoding="utf-8")
        return True
    return False


# Pages whose frontmatter I rewrote manually — preserve their YAML
MANUAL_FM = {
    "index.qmd",
    "a_propos.qmd",
    "bildungsplan.qmd",
    "programme.qmd",
    "remerciements.qmd",
    "annexes/competences.qmd",
    "annexes/erreurs_typiques.qmd",
    "annexes/glossaire.qmd",
    "annexes/grille_evaluation.qmd",
    "annexes/strategies.qmd",
    "_quarto.yml",
}


def main() -> None:
    n = 0
    for p in ROOT.rglob("*.qmd"):
        if any(part in EXCLUDE_DIRS for part in p.parts):
            continue
        if p.name in SKIP_FILES:
            continue
        rel = p.relative_to(ROOT).as_posix()
        manage_fm = rel not in MANUAL_FM
        if process(p, manage_fm):
            n += 1
    print(f"rewritten {n} files")


if __name__ == "__main__":
    main()
