#!/usr/bin/env python3
"""Audit every PDF under static/ for /Author=Le Boulanger.

Standalone gate — was previously embedded inside the non-blocking
exam-render step in the qmd-era workflow (commit 49ce54c). Decoupled here
so it runs unconditionally over both:
  - static/downloads/             (exam PDFs from the hybrid Quarto step)
  - static/materials/worksheets/  (worksheet placeholders generated by
                                   _scripts/make_materials.py)

Hard-fail on any PDF whose /Author metadata field doesn't contain the
substring 'Le Boulanger' (case-insensitive).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCAN_DIRS = (
    REPO / "static" / "downloads",
    REPO / "static" / "materials" / "worksheets",
)


def main() -> int:
    try:
        from pypdf import PdfReader
    except ImportError:  # pragma: no cover
        print("::error::pypdf not installed", file=sys.stderr)
        return 1

    pdfs = []
    for d in SCAN_DIRS:
        if d.exists():
            pdfs.extend(sorted(d.rglob("*.pdf")))

    if not pdfs:
        print("No PDFs found under static/ — nothing to audit.")
        return 0

    bad: list[tuple[Path, str]] = []
    for p in pdfs:
        try:
            r = PdfReader(str(p))
            author = (r.metadata or {}).get("/Author", "") or ""
        except Exception as exc:  # pragma: no cover
            bad.append((p, f"<read error: {exc}>"))
            continue
        if "le boulanger" not in str(author).lower():
            bad.append((p, str(author) or "<empty>"))

    if bad:
        print(f"::error::PDF author audit failed ({len(bad)}/{len(pdfs)}):",
              file=sys.stderr)
        for p, a in bad[:25]:
            print(f"  {p.relative_to(REPO)}: /Author={a!r}", file=sys.stderr)
        if len(bad) > 25:
            print(f"  ... and {len(bad) - 25} more", file=sys.stderr)
        return 1

    print(f"All {len(pdfs)} PDFs attributed to S. Le Boulanger.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
